### ISSUE TITLE
Couldn't we (shouldn't we!) think of a piss chin as a function for composing streams?

### ISSUE THREAD

**Issue by rjmk** [FilWisher/pisschin#1]
Or indeed a stream is itself!
- The streams are the buffers / sources 
- We encode lengths as takes/take whiles (takes while?)
- Performing structural regex patterns becomes mapping over streams

Of course this is at a much higher level of abstraction than the C code you're discussing (for example, where are the pointers to the next and previous streams? Probably not in the streams themselves, but ultimately that's George's problem)

**Comment by FilWisher** [comment]
That is a very nice way to thing about piss chins I think. We can do almost everything without ever touching the data. Then, when someone wants the actual data, we pull the stream through.

Since watching the SICP lectures, George seems to have been lumbered with a lot of responsibilities!
